### PR TITLE
Run GitHub action on GitHub runners

### PR DESCRIPTION
**Pull request by devguyio**
This PR is for running the GitHub action on GitHub runner.

Changes:
- Set an `integration` build flag for integration tests.
- Change the GitHub Action workflow to run unit tests followed by integration tests.

Stacked on #93 & #94

### CODE REVIEW

**Comment by purplefox** [comment]
There seem to be a lot of changes in here not related to the github actions changes. Was that deliberate?

**Comment by devguyio** [comment]
> There seem to be a lot of changes in here not related to the github actions changes. Was that deliberate?

The formatting in the integration tests where I added a build flag :/ we need some common editor config file to get rid of this problem. 

Would you like me to remove those changes for now? I can do that.

**Comment by devguyio** [comment]
One test failde, seems a flake
```
=== FAIL: repli TestInsufficientReplicas (0.06s)
    replication_test.go:146: 
        	Error Trace:	/home/runner/work/tektite/tektite/repli/replication_test.go:146
        	Error:      	Not equal: 
        	            	expected: "replicator is paused"
        	            	actual  : "replicator is not initialised"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-replicator is paused
        	            	+replicator is not initialised
        	Test:       	TestInsufficientReplicas

```

**Comment by purplefox** [comment]
> The formatting in the integration tests where I added a build flag :/ we need some common editor config file to get rid of this problem.

> Would you like me to remove those changes for now? I can do that.

Yes, I think its best to keep the PRs clean. If we want to reformat, we can do that in a different PR.

Regarding formatting, I think I just have goland defaults, are you using a specific format file?

**Comment by devguyio** [comment]
> > The formatting in the integration tests where I added a build flag :/ we need some common editor config file to get rid of this problem.
> 
> > Would you like me to remove those changes for now? I can do that.
> 
> Yes, I think its best to keep the PRs clean. If we want to reformat, we can do that in a different PR.
> 
> Regarding formatting, I think I just have goland defaults, are you using a specific format file?

Fixed. 

Yeah I've a few difference, for example I order the imports (stdlib, 3rd party, our project) and I set a column with limit

**Review by purplefox — APPROVED** [review]
LGTM

**Pull request merged**
