### PR TITLE
Enhance the README file with more Tektite info

### PR DESCRIPTION
**Pull request by devguyio**
[Updated 19.06.2024]
I pushed a small enhancement increment with the logo and we can move the diagrams to another round of enhancement.

### CODE REVIEW

**Comment by purplefox** [comment]
Thanks for this! I like the community / getting started sections, but I think we should keep the "what is tektite", features etc in the documentation, as they seem to be a duplication of that. If we have stuff like that in two places we'll end up with two competing sets of "docs" and we'll have to update things in two places when they change and they're probably end up diverging.

**Comment by devguyio** [comment]
> Thanks for this! I like the community / getting started sections, but I think we should keep the "what is tektite", features etc in the documentation, as they seem to be a duplication of that. If we have stuff like that in two places we'll end up with two competing sets of "docs" and we'll have to update things in two places when they change and they're probably end up diverging.

I understand that being duplicated is adds the burden of keeping them in sync, but the reason I added them is because I believe the README is the no. 1 place that should grab the attention of the user. So the first half of the README should be so exciting and compelling to make the user wanna jump to the documentation, download the software, play around with it, jump to slack etc.

That is why I intentionally added the features and screenshots cause I believe those are very impressive and very attractive. I think at the current stage with the project being not well known yet, it should be acceptable to accept the tax of keeping the README in sync, for the favor of attracting more users. 

What do you think? Maybe we can try and see if we end up doing a horrible job keeping it up-to-date, we can remove those.

**Comment by devguyio** [comment]
Here are a few examples that follow this approach:
- [vcluster](https://github.com/loft-sh/vcluster)
- [bubbletea](https://github.com/charmbracelet/bubbletea/)

**Comment by purplefox** [comment]
LGTM. Thanks!

**Pull request merged**
