### PR TITLE
Fix the "kafka in" example in concepts page

### PR DESCRIPTION
**Pull request by devguyio**
The "kafka in" example in the concepts page was missing a "partitions" argument.

### CODE REVIEW

**Comment by purplefox** [comment]
@devguyio Can you please execute `mkdocs build` from the docs branch root (you will need to install material for mkdocs). that will build the actual site, and include the changed site in the PR too.

**Comment by purplefox** [comment]
Ideally we should have a GH action that builds it, but for now its manual.

**Comment by purplefox** [comment]
If it's a problem to get mkdocs working on Linux (?) I can build it here.

**Comment by devguyio** [comment]
> If it's a problem to get mkdocs working on Linux (?) I can build it here.

@purplefox not at all, I just wasn't sure if I'm supposed to push that as well. Fixed. Note that it also bumped up the `mkdocs-material` version, hope that's fine.

**Pull request merged**
