### PR TITLE
feat: add script tests for remaining functions.

### LINKED ISSUE #45: Script test for all functions
We should create a script test testing all available functions.

### PR DESCRIPTION
**Pull request by vchandela**
fixes #45 

-  Script test already added for `if()` in this PR: https://github.com/spirit-labs/tektite/pull/146
- Adding script tests for remaining functions. 
- Combined all the script tests in `builtin_functions_`

- Tested locally
image

### CODE REVIEW

**Comment by purplefox** [comment]
I would suggest putting all the function tests in the same script file, or you will end up with a lot of files!

**Comment by vchandela** [comment]
> I would suggest putting all the function tests in the same script file, or you will end up with a lot of files!

sure. I'll merge all these files together in the final commit.

**Comment by purplefox** [comment]
Tests seem to be failing on this.

**Comment by vchandela** [comment]
> Tests seem to be failing on this.

3 UTs are failing that seem unrelated to the changes in this PR.

**Comment by purplefox** [comment]
The failure isn't unrelated, if you look at the output in the run you will see this:

```
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -361,7 +361,5 @@
        	            	 +------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
        	            	-| 0                    | 2006-01-02 15:04:05.000000 | key01                                          | .                                              | {"v0": 1,"v1": 1.23,"v2": true,"v3": "123456.. |
        	            	-| 0                    | 2006-01-02 15:06:05.000000 | key03                                          | .                                              | {"v0": 1,"v1": 3.23,"v2": true,"v3": "323456.. |
        	            	-| 1                    | 2006-01-02 15:10:05.000000 | key07                                          | .                                              | {"v0": 3,"v1": 7.23,"v2": true,"v3": "723456.. |
        	            	-+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
        	            	-3 rows returned
        	            	+| 1                    | 2006-01-02 15:10:05.000000 | key07                                          | .                                              | {"v0": 3,"v1": 7.23,"v2": true,"v3": "723456.. |
        	            	++------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
        	            	+1 row returned
        	            	 (scan all from toUpperTopic) -> (sort by key);
        	Test:       	TestScriptThreeNodes/TestScript/builtin_functions
```

**Comment by purplefox** [comment]
This means your test isn't matching expected output

**Comment by vchandela** [comment]
> This means your test isn't matching expected output

Added a fix. This change was in my local. I missed merging it yesterday. Sorry.

**Pull request merged**
