### PR TITLE
Use pointer to type in config to represent unset config setting

### PR DESCRIPTION
**Pull request by hxalid**
It is a draft PR for https://github.com/spirit-labs/tektite/issues/36 that just works, but requires more polish up.

Changes:
- Upgrade Kong from v0.2.17 to v0.9.0 in order we can use pointers. See https://github.com/alecthomas/kong/issues/196 for more information why it is needed.
- Refactor all the config fields except `TLSConfig` and `[]string` types to be pointers. (Will think if it makes to make them pointer as well)
-  cmd/tektited/runner_test.go will need to be handled something differently as testify does not seem to support pointer fields, one of the relevant issues for more info: https://github.com/stretchr/testify/issues/535 
- The default values and the validate function will need to be revised: 
- How are we actually going to differentiate between an empty value and a nil value? For instance, should we panic in the validation if a specific value is nil or we should assign a default value and keep moving on? 
- If we are going to set a default value for every nil config parameter, then what is the point of not using that default value instead of the nil config parameter at the first place? 
- If we are not going to set a default value and let a specific config parameter be nil when it is not explicitly set, then we are opening up a potential segmentation fault somewhere up in the chain.
- To avoid segmentation faults in those kind of situations, we will have to have nil check before each time a config parameter is used. This can be done in the validate function, but then the expectation is that every parameter should have some default value.

### CODE REVIEW

**Comment by purplefox** [comment]
> If we are going to set a default value for every nil config parameter, then what is the point of not using that default value instead of the nil config parameter at the first place?

Agreed, if we provide a "constructor" for `conf.Config` so its always created with defaults initialised, then we don't need pointers or the `ApplyDefaults` method, and it becomes a lot simpler?

I haven't thought it fully through, but if that makes sense, let's do that. I'm all for doing the simplest thing that works.

**Comment by purplefox** [comment]
Hi @hxalid any further thoughts on this? :)

**Comment by hxalid** [comment]
> Hi @hxalid any further thoughts on this? :)

Hi @purplefox - apologies for disappearance here :). I hope to get back to this within the next couple of days. I think I am good with the constructor idea, but I need to do a quick test to see if we can avoid using ApplyDefaults (or whatever we rename it to). In any case, we will have it implemented in one or the other way.

**Comment by purplefox** [comment]
Folks, I'm going to close this. Feel free to re-open it if work restarts on it.

**Pull request closed without merging**
